name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create deployment package
        run: zip -r deploy.zip . -x "*.git*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Test AWS connection
        run: aws sts get-caller-identity

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.MY_AWS_SECRET_KEY }}
          application_name: fullstack-devops-project
          environment_name: Fullstack-devops-project-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
          use_existing_version_if_available: true
